name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Cargo clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Cargo test
        run: cargo test --no-default-features